export const ALL_TOPICS = 'ALL_TOPICS'
export const ALL_QUESTIONS = 'ALL_QUESTIONS'
export const RIGHT_ANSWER = 'RIGHT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'
// export const COUNT_SCORE = 'COUNT_SCORE'
